// Generated by gencpp from file motors_data_msgs_ros1/TfFeedback.msg
// DO NOT EDIT!


#ifndef MOTORS_DATA_MSGS_ROS1_MESSAGE_TFFEEDBACK_H
#define MOTORS_DATA_MSGS_ROS1_MESSAGE_TFFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motors_data_msgs_ros1
{
template <class ContainerAllocator>
struct TfFeedback_
{
  typedef TfFeedback_<ContainerAllocator> Type;

  TfFeedback_()
    : x(0.0)
    , y(0.0)
    , rot(0.0)  {
    }
  TfFeedback_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , rot(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _rot_type;
  _rot_type rot;





  typedef boost::shared_ptr< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TfFeedback_

typedef ::motors_data_msgs_ros1::TfFeedback_<std::allocator<void> > TfFeedback;

typedef boost::shared_ptr< ::motors_data_msgs_ros1::TfFeedback > TfFeedbackPtr;
typedef boost::shared_ptr< ::motors_data_msgs_ros1::TfFeedback const> TfFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator1> & lhs, const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.rot == rhs.rot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator1> & lhs, const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motors_data_msgs_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03b81cae7f2c85f753929002066a5643";
  }

  static const char* value(const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03b81cae7f2c85f7ULL;
  static const uint64_t static_value2 = 0x53929002066a5643ULL;
};

template<class ContainerAllocator>
struct DataType< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motors_data_msgs_ros1/TfFeedback";
  }

  static const char* value(const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 rot\n"
;
  }

  static const char* value(const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.rot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TfFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motors_data_msgs_ros1::TfFeedback_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "rot: ";
    Printer<float>::stream(s, indent + "  ", v.rot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTORS_DATA_MSGS_ROS1_MESSAGE_TFFEEDBACK_H
